import type { components } from './types.js';

export type ApiSchemaHomeUserDtoAuth = components['schemas']['home-user.dto.auth'];
export type ApiSchemaHomeUserEntityUser = components['schemas']['home-user.entity.user'];
export type ApiSchemaHomeUserDtoPassport = components['schemas']['home-user.dto.passport'];
export type ApiSchemaAJwtDtoJwtToken = components['schemas']['a-jwt.dto.jwtToken'];
export type ApiSchemaHomeUserDtoPassportJwt = components['schemas']['home-user.dto.passportJwt'];
export type ApiSchemaAAuthsimpleDtoAuthSimple = components['schemas']['a-authsimple.dto.authSimple'];
export type ApiSchemaAMenuDtoMenuGroup = components['schemas']['a-menu.dto.menuGroup'];
export type ApiSchemaAMenuDtoMenuItemMeta = components['schemas']['a-menu.dto.menuItemMeta'];
export type ApiSchemaAMenuDtoMenuItem = components['schemas']['a-menu.dto.menuItem'];
export type ApiSchemaAMenuDtoMenus = components['schemas']['a-menu.dto.menus'];
export type ApiSchemaASsrcabloyDtoErrorData = components['schemas']['a-ssrcabloy.dto.errorData'];
export type ApiSchemaTestSsrDtoTestDetail = components['schemas']['test-ssr.dto.testDetail'];
export type ApiSchemaTestSsrDtoTestResult = components['schemas']['test-ssr.dto.testResult'];
export type ApiSchemaTestSsrDtoTestBody = components['schemas']['test-ssr.dto.testBody'];
export type ApiSchemaTestSsrDtoTestParams = components['schemas']['test-ssr.dto.testParams'];
export type ApiSchemaTestSsrDtoTestQuery = components['schemas']['test-ssr.dto.testQuery'];
export type ApiSchemaTestVonaDtoUser = components['schemas']['test-vona.dto.user'];
export type ApiSchemaTestVonaDtoProfile = components['schemas']['test-vona.dto.profile'];
