packages:
  - 'cabloy-cli'
  - 'cli'
  - 'cli-set-front'

hoist: true
hoistWorkspacePackages: true
linkWorkspacePackages: 'deep'
preferWorkspacePackages: true
autoInstallPeers: true
publicHoistPattern:
  - '*eslint*'
  - '*types*'
  - 'lerna'
  - 'cabloy'
  - '@cabloy'
  - '*cabloy*'
  - '*@cabloy*'
  - '*zova*'

overrides:
  '@cabloy/module-info': 'npm:@cabloy/module-info@^2.0.0'
